// Auth
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_TOKEN = 'ADD_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';
export const CLEAR_ANONYMOUSLY = 'CLEAR_ANONYMOUSLY';
export const UPDATE_MANAGEMENT = 'UPDATE_MANAGEMENT';
export const UPDATE_DEVELOPER_MODE = 'UPDATE_DEVELOPER_MODE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RESET_STATE = 'RESET_STATE';
export const UPDATE_PRIVACY_POLICY_DATE = 'UPDATE_PRIVACY_POLICY_DATE';

export const ON_LOGIN = 'ON_LOGIN';
export const GET_CHECKLISTS = 'GET_CHECKLISTS';
export const SAVE_CHECKLIST_CATEGORY = 'SAVE_CHECKLIST_CATEGORY';
export const SAVE_PENDING = 'SAVE_PENDING';
export const REMOVE_PENDING = 'REMOVE_PENDING';
export const SAVE_DRAFT = 'SAVE_DRAFT';
export const REMOVE_DRAFT = 'REMOVE_DRAFT';
export const SET_NETWORK_STATE = 'SET_NETWORK_STATE';
export const GET_INCIDENCES = 'GET_INCIDENCES';

// Canteens
export const GET_CANTEENS = 'GET_CANTEENS';
export const SET_CANTEENS = 'SET_CANTEENS';
export const SET_BUILDINGS = 'SET_BUILDINGS';
export const SET_SELECTED_CANTEEN = 'SET_SELECTED_CANTEEN';
export const SET_SELECTED_CANTEEN_FOOD_OFFERS =
  'SET_SELECTED_CANTEEN_FOOD_OFFERS';
export const SET_SELECTED_CANTEEN_FOOD_OFFERS_LOCAL =
  'SET_SELECTED_CANTEEN_FOOD_OFFERS_LOCAL';
export const SET_BUSINESS_HOURS = 'SET_BUSINESS_HOURS';
export const SET_BUSINESS_HOURS_GROUPS = 'SET_BUSINESS_HOURS_GROUPS';
export const SET_SELECTED_FOOD_MARKINGS = 'SET_SELECTED_FOOD_MARKINGS';
export const SET_CANTEEN_FEEDBACK_LABELS = 'SET_CANTEEN_FEEDBACK_LABELS';
export const SET_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES =
  'SET_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES';
export const UPDATE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES =
  'UPDATE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES';
export const DELETE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES =
  'DELETE_OWN_CANTEEN_FEEDBACK_LABEL_ENTRIES';

// Settings
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_POPUP_EVENTS = 'SET_POPUP_EVENTS';
export const SET_WARNING = 'SET_WARNING';
export const SET_SORTING = 'SET_SORTING';
export const SET_CAMPUSES_SORTING = 'SET_CAMPUSES_SORTING';
export const SET_APARTMENTS_SORTING = 'SET_APARTMENTS_SORTING';
export const SET_SERVER_INFO = 'SET_SERVER_INFO';
export const SET_COLOR = 'SET_COLOR';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_DRAWER_POSITION = 'SET_DRAWER_POSITION';
export const SET_APP_SETTINGS = 'SET_APP_SETTINGS';
export const SET_WIKIS_PAGES = 'SET_WIKIS_PAGES';
export const SET_WIKIS = 'SET_WIKIS';
export const SET_NICKNAME_LOCAL = 'SET_NICKNAME_LOCAL';
export const SET_FIRST_DAY_OF_THE_WEEK = 'SET_FIRST_DAY_OF_THE_WEEK';
export const SET_AMOUNT_COLUMNS_FOR_CARDS = 'SET_AMOUNT_COLUMNS_FOR_CARDS';
// Food Feedback Labels
export const SET_FOOD_COLLECTION = 'SET_FOOD_COLLECTION';
export const SET_FOOD_CATEGORIES = 'SET_FOOD_CATEGORIES';
export const SET_FOOD_OFFERS_CATEGORIES = 'SET_FOOD_OFFERS_CATEGORIES';
export const UPDATE_FOOD_FEEDBACK_LABELS = 'UPDATE_FOOD_FEEDBACK_LABELS';
export const UPDATE_OWN_FOOD_FEEDBACK = 'UPDATE_OWN_FOOD_FEEDBACK';
export const UPDATE_FOOD_FEEDBACK_LOCAL = 'UPDATE_FOOD_FEEDBACK_LOCAL';
export const DELETE_FOOD_FEEDBACK_LOCAL = 'DELETE_FOOD_FEEDBACK_LOCAL';
export const UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES =
  'UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES';
export const UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL =
  'UPDATE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL';
export const DELETE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL =
  'DELETE_OWN_FOOD_FEEDBACK_LABEL_ENTRIES_LOCAL';
export const UPDATE_MARKINGS = 'UPDATE_MARKINGS';
export const SET_MARKING_DETAILS = 'SET_MARKING_DETAILS';
export const SET_MOST_LIKED_FOODS = 'SET_MOST_LIKED_FOODS';
export const SET_MOST_DISLIKED_FOODS = 'SET_MOST_DISLIKED_FOODS';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';

// Food Attributes
export const SET_FOOD_ATTRIBUTE_GROUPS = 'SET_FOOD_ATTRIBUTE_GROUPS';
export const SET_FOOD_ATTRIBUTES = 'SET_FOOD_ATTRIBUTES';
export const SET_FOOD_ATTRIBUTES_DICT = 'SET_FOOD_ATTRIBUTES_DICT';

// News
export const SET_NEWS = 'SET_NEWS';

// Campus

export const SET_CAMPUSES = 'SET_CAMPUSES';
export const SET_CAMPUSES_DICT = 'SET_CAMPUSES_DICT';
export const SET_CAMPUSES_LOCAL = 'SET_CAMPUSES_LOCAL';
export const SET_UNSORTED_CAMPUSES = 'SET_UNSORTED_CAMPUSES';

//Apartment
export const SET_APARTMENTS = 'SET_APARTMENTS';
export const SET_APARTMENTS_DICT = 'SET_APARTMENTS_DICT';
export const SET_APARTMENTS_LOCAL = 'SET_APARTMENTS_LOCAL';
export const SET_UNSORTED_APARTMENTS = 'SET_UNSORTED_APARTMENTS';

//Management

export const SET_DAY_PLAN = 'SET_DAY_PLAN';
export const SET_FOOD_PLAN = 'SET_FOOD_PLAN';
export const SET_WEEK_PLAN = 'SET_WEEK_PLAN';

//FORM

export const SET_FORM_FILTER = 'SET_FORM_FILTER';
export const SET_FORM_SUBMISSION = 'SET_FORM_SUBMISSION';

// APP ELEMENTS

export const SET_APP_ELEMENTS = 'SET_APP_ELEMENTS';

//COLLECTION DATES LAST UPDATES

export const SET_COLLECTION_DATES_LAST_UPDATED =
  'SET_COLLECTION_DATES_LAST_UPDATED';

// Clear States

export const CLEAR_NEWS = 'CLEAR_NEWS';
export const CLEAR_FOODS = 'CLEAR_FOODS';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';
export const CLEAR_CANTEENS = 'CLEAR_CANTEENS';
export const CLEAR_CAMPUSES = 'CLEAR_CAMPUSES';
export const CLEAR_MANAGEMENT = 'CLEAR_MANAGEMENT';
export const CLEAR_APARTMENTS = 'CLEAR_APARTMENTS';
export const CLEAR_FORM = 'CLEAR_FORM';
export const CLEAR_FOOD_ATTRIBUTES = 'CLEAR_FOOD_ATTRIBUTES';
export const CLEAR_APP_ELEMENTS = 'CLEAR_APP_ELEMENTS';
export const CLEAR_COLLECTION_DATES_LAST_UPDATED =
  'CLEAR_COLLECTION_DATES_LAST_UPDATED';
