import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  sheetView: {
    width: '100%',
    height: '100%',
    borderTopRightRadius: 28,
    borderTopLeftRadius: 28,
    padding: 10,
    paddingBottom: 0,
  },
  contentContainer: {
    alignItems: 'center',
  },
  sheetHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 28,
    borderTopLeftRadius: 28,
  },
  sheetcloseButton: {
    width: 45,
    height: 45,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sheetHeading: {
    fontFamily: 'Poppins_700Bold',
  },
  editContentContainer: {
    width: '100%',
    paddingHorizontal: 10,
    marginTop: 30,
  },
  inputContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    gap: 0,
    borderWidth: 1,
    borderColor: '#3A3A3A',
  },
  input: {
    width: '100%',
    height: 50,
    borderRadius: 10,
    paddingHorizontal: 20,
    fontFamily: 'Poppins_400Regular',
    borderWidth: 1,
    outline: 'none',
    outlineColor: 'transparent',
    borderColor: '#3A3A3A',
    fontSize: 16,
  },
  button: {
    width: 150,
    height: 44,
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  buttonLabel: {
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
  },
  modalSubHeading: {
    width: '95%',
    fontSize: 18,
    fontFamily: 'Poppins_400Regular',
    marginTop: 30,
    marginBottom: 10,
    textAlign: 'center',
  },
  actionContainer: {
    width: '90%',
    gap: 15,
    alignItems: 'center',
    marginTop: 20,
  },
  loginButton: {
    width: '80%',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
  },
  loginLabel: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#2E2E2E',
  },
  dummy: {},
});
