# SonarCloud configuration for Rocket Meals
sonar.projectKey=rocket-meals_rocket-meals
sonar.organization=rocket-meals

# Combine all exclusions in a single line
sonar.exclusions=**/dist/**,**/build/**,**/node_modules/**,**/leaflet.html,**/leaflet/index.html,**/leaflet*.js,**/leaflet*.min.js,**/leaflet/**/*.js,**/generate-types/index.js,**/*.min.js,**/coverage/**,**/public/assets/**,**/__tests__/**,**/*.html

# Coverage exclusions
sonar.coverage.exclusions=**/dist/**,**/build/**,**/node_modules/**,**/leaflet.html,**/leaflet/index.html,**/leaflet*.js,**/leaflet*.min.js,**/leaflet/**/*.js,**/generate-types/index.js,**/*.min.js,**/coverage/**,**/__tests__/**,**/*spec*/**,apps/frontend/app/**

# Source directories
sonar.sources=.
sonar.sourceEncoding=UTF-8
