// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
//
// Generated by packages/common/licenses/collectLicenses.cjs, which is
// invoked from this app's metro.config.js on every bundler start
// (expo start / expo export / EAS build). It lists the currently
// installed direct dependencies of this app and of its workspace
// packages (repo-depkit-common, repo-depkit-common-ui, ...).
//
// The file is committed so type checks and tests work without running
// Metro; it rewrites itself whenever the installed dependencies change.

import type { LicensePackageInfo } from 'repo-depkit-common-ui';

const licenses: LicensePackageInfo[] = [
	{ name: "@babel/runtime", version: "7.28.4", license: "MIT", repository: "https://github.com/babel/babel", licenseUrl: "https://github.com/babel/babel/blob/HEAD/packages/babel-runtime/LICENSE" },
	{ name: "@dicebear/collection", version: "9.4.2", license: "MIT", repository: "https://github.com/dicebear/dicebear", licenseUrl: "https://github.com/dicebear/dicebear/blob/HEAD/LICENSE" },
	{ name: "@dicebear/core", version: "9.4.2", license: "MIT", repository: "https://github.com/dicebear/dicebear", licenseUrl: "https://github.com/dicebear/dicebear/blob/HEAD/LICENSE" },
	{ name: "@expo/vector-icons", version: "15.0.3", license: "MIT", repository: "https://github.com/expo/vector-icons", licenseUrl: "https://github.com/expo/vector-icons/blob/HEAD/LICENSE" },
	{ name: "@gorhom/bottom-sheet", version: "5.2.9", license: "MIT", repository: "https://github.com/gorhom/react-native-bottom-sheet", licenseUrl: "https://github.com/gorhom/react-native-bottom-sheet/blob/HEAD/LICENSE" },
	{ name: "@mapbox/vector-tile", version: "1.3.1", license: "BSD-3-Clause", repository: "https://github.com/mapbox/vector-tile-js", licenseUrl: "https://github.com/mapbox/vector-tile-js/blob/HEAD/LICENSE.txt" },
	{ name: "@react-navigation/drawer", version: "7.7.5", license: "MIT", repository: "https://github.com/react-navigation/react-navigation", licenseUrl: "https://github.com/react-navigation/react-navigation/blob/HEAD/packages/drawer/LICENSE" },
	{ name: "@reduxjs/toolkit", version: "2.11.2", license: "MIT", repository: "https://github.com/reduxjs/redux-toolkit", licenseUrl: "https://github.com/reduxjs/redux-toolkit/blob/HEAD/LICENSE" },
	{ name: "buffer", version: "6.0.3", license: "MIT", repository: "https://github.com/feross/buffer", licenseUrl: "https://github.com/feross/buffer/blob/HEAD/LICENSE" },
	{ name: "expo", version: "54.0.20", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-asset", version: "12.0.10", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-audio", version: "1.0.16", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-build-properties", version: "1.0.9", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-clipboard", version: "8.0.7", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-constants", version: "18.0.10", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-document-picker", version: "14.0.7", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-file-system", version: "19.0.19", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-font", version: "14.0.9", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-image-picker", version: "17.0.8", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-linking", version: "8.0.9", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-localization", version: "17.0.7", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-location", version: "19.0.7", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-notifications", version: "0.32.13", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-router", version: "6.0.15", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-secure-store", version: "15.0.7", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-speech", version: "14.0.8", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-splash-screen", version: "31.0.11", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-sqlite", version: "16.0.10", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-status-bar", version: "3.0.8", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-system-ui", version: "6.0.8", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-task-manager", version: "14.0.9", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-updates", version: "29.0.16", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "expo-web-browser", version: "15.0.9", license: "MIT", repository: "https://github.com/expo/expo", licenseUrl: "https://github.com/expo/expo" },
	{ name: "moment-timezone", version: "0.5.48", license: "MIT", repository: "https://github.com/moment/moment-timezone", licenseUrl: "https://github.com/moment/moment-timezone/blob/HEAD/LICENSE" },
	{ name: "pbf", version: "3.3.0", license: "BSD-3-Clause", repository: "https://github.com/mapbox/pbf", licenseUrl: "https://github.com/mapbox/pbf/blob/HEAD/LICENSE" },
	{ name: "react", version: "19.1.0", license: "MIT", repository: "https://github.com/facebook/react", licenseUrl: "https://github.com/facebook/react/blob/HEAD/packages/react/LICENSE" },
	{ name: "react-dom", version: "19.1.0", license: "MIT", repository: "https://github.com/facebook/react", licenseUrl: "https://github.com/facebook/react/blob/HEAD/packages/react-dom/LICENSE" },
	{ name: "react-native", version: "0.81.5", license: "MIT", repository: "https://github.com/facebook/react-native", licenseUrl: "https://github.com/facebook/react-native/blob/HEAD/packages/react-native/LICENSE" },
	{ name: "react-native-calendars", version: "1.1313.0", license: "MIT", repository: "https://github.com/wix/react-native-calendars", licenseUrl: "https://github.com/wix/react-native-calendars/blob/HEAD/LICENSE" },
	{ name: "react-native-gesture-handler", version: "2.28.0", license: "MIT", repository: "https://github.com/software-mansion/react-native-gesture-handler", licenseUrl: "https://github.com/software-mansion/react-native-gesture-handler/blob/HEAD/LICENSE" },
	{ name: "react-native-qrcode-svg", version: "6.3.20", license: "MIT", repository: "https://github.com/Expensify/react-native-qrcode-svg", licenseUrl: "https://github.com/Expensify/react-native-qrcode-svg/blob/HEAD/LICENSE" },
	{ name: "react-native-reanimated", version: "4.1.5", license: "MIT", repository: "https://github.com/software-mansion/react-native-reanimated", licenseUrl: "https://github.com/software-mansion/react-native-reanimated/blob/HEAD/packages/react-native-reanimated/LICENSE" },
	{ name: "react-native-safe-area-context", version: "5.6.2", license: "MIT", repository: "https://github.com/AppAndFlow/react-native-safe-area-context", licenseUrl: "https://github.com/AppAndFlow/react-native-safe-area-context/blob/HEAD/LICENSE" },
	{ name: "react-native-screens", version: "4.16.0", license: "MIT", repository: "https://github.com/software-mansion/react-native-screens", licenseUrl: "https://github.com/software-mansion/react-native-screens/blob/HEAD/LICENSE" },
	{ name: "react-native-svg", version: "15.12.1", license: "MIT", repository: "https://github.com/react-native-community/react-native-svg", licenseUrl: "https://github.com/react-native-community/react-native-svg/blob/HEAD/LICENSE" },
	{ name: "react-native-web", version: "0.21.2", license: "MIT", repository: "https://github.com/necolas/react-native-web", licenseUrl: "https://github.com/necolas/react-native-web/blob/HEAD/LICENSE" },
	{ name: "react-native-webview", version: "13.15.0", license: "MIT", repository: "https://github.com/react-native-webview/react-native-webview", licenseUrl: "https://github.com/react-native-webview/react-native-webview/blob/HEAD/LICENSE" },
	{ name: "react-redux", version: "9.2.0", license: "MIT", repository: "https://github.com/reduxjs/react-redux", licenseUrl: "https://github.com/reduxjs/react-redux/blob/HEAD/LICENSE.md" },
	{ name: "setimmediate", version: "1.0.5", license: "MIT", repository: "https://github.com/YuzuJS/setImmediate", licenseUrl: "https://github.com/YuzuJS/setImmediate/blob/HEAD/LICENSE.txt" },
	{ name: "tinycolor2", version: "1.6.0", license: "MIT", repository: "https://github.com/bgrins/TinyColor", licenseUrl: "https://github.com/bgrins/TinyColor/blob/HEAD/LICENSE" },
];

export default licenses;
