// @ts-nocheck

export enum AccessibilityRoles {
    none = 'none',
    button = 'button',
    link = 'link',
    search = 'search',
    image = 'image',
    keyboardkey = 'keyboardkey',
    text = 'text',
    adjustable = 'adjustable',
    imagebutton = 'imagebutton',
    header = 'header',
    summary = 'summary',
    alert = 'alert',
    checkbox = 'checkbox',
    combobox = 'combobox',
    menu = 'menu',
    menubar = 'menubar',
    menuitem = 'menuitem',
    progressbar = 'progressbar',
    radio = 'radio',
    radiogroup = 'radiogroup',
    scrollbar = 'scrollbar',
    spinbutton = 'spinbutton',
    switch = 'switch',
    tab = 'tab',
    tablist = 'tablist',
    timer = 'timer',
    toolbar = 'toolbar'
}
