name: Backend Directus Extension Build

# Temporary disabled
#on:
#  push:
#    paths:
#      - 'backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          registry-url: 'https://registry.npmjs.org'

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🚀 Build the extension
        run: yarn run build

      - name: 🔍 Check if api.js has changed
        id: check_changes
        run: |
          if git status --porcelain ./dist/api.js | grep -q 'M'; then
            echo "api_js_changed=true" >> $GITHUB_ENV
          else
            echo "api_js_changed=false" >> $GITHUB_ENV
          fi

      - name: ✅ Commit and push changes if api.js changed
        if: env.api_js_changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./dist/api.js
          git commit -m "Updated dist/api.js after build"
          git push
