// Auto-generated by scripts/generate-tts-voices.py
// Do not edit manually – re-run the generate-tts-voices workflow instead.

export type GeneratedVoiceEntry = {
	text: string;
	audio: number; // Metro require() asset ID
};

// This file is a placeholder. Run the generate-tts-voices workflow
// or `python scripts/generate-tts-voices.py` to populate it with
// actual voice entries and their corresponding MP3 require() mappings.
export const generatedVoices: Record<string, GeneratedVoiceEntry> = {};
