import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	editImageButton: {
		position: 'absolute',
		bottom: 10,
		left: 5,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		width: 35,
		height: 35,
		borderRadius: 50,
		backgroundColor: 'rgba(0,0,0,0.2)',
	},
        overlayActionsContainer: {
                position: 'absolute',
                top: 5,
                right: 5,
                flexDirection: 'column',
                alignItems: 'flex-end',
                gap: 10,
        },
        overlayIconButton: {
                width: 35,
                height: 35,
                borderRadius: 50,
                backgroundColor: 'rgba(0,0,0,0.2)',
                justifyContent: 'center',
                alignItems: 'center',
        },
        favContainer: {
                width: 35,
                height: 35,
                borderRadius: 50,
                backgroundColor: 'rgba(0,0,0,0.45)',
                justifyContent: 'center',
                alignItems: 'center',
        },
        favContainerWarn: {
                width: 35,
                height: 35,
                borderRadius: 50,
                backgroundColor: 'rgba(255, 255, 255, 0.85)',
                justifyContent: 'center',
                alignItems: 'center',
        },
        aiBadgeContainer: {
                width: 35,
                height: 35,
                borderRadius: 50,
                backgroundColor: 'rgba(0,0,0,0.6)',
                justifyContent: 'center',
                alignItems: 'center',
        },
        categoriesContainer: {
                gap: 5,
                width: 35,
                position: 'absolute',
                top: 5,
                left: 5,
                justifyContent: 'flex-start',
                alignItems: 'center',
        },
        categoryLogo: {
                width: 35,
                height: 35,
                resizeMode: 'cover',
        },
	foodName: {
		fontSize: 16,
		fontFamily: 'Poppins_400Regular',
		textAlign: 'center',
	},
	priceButton: {
		width: '100%',
		height: 35,
		backgroundColor: 'white',
		borderRadius: 18,
		alignItems: 'center',
		justifyContent: 'center',
	},
	price: {
		fontSize: 16,
		fontFamily: 'Poppins_700Bold',
		textAlign: 'center',
		marginTop: 2,
	},
	heading: {
		fontSize: 40,
		fontFamily: 'Poppins_700Bold',
		textAlign: 'center',
	},
        priceTag: {
                position: 'absolute',
                bottom: 10,
                right: 10,
                backgroundColor: 'rgba(0, 0, 0, 0.7)',
                paddingVertical: 5,
                paddingHorizontal: 10,
                borderRadius: 5,
        },
        priceText: {
                color: '#FFF',
                fontSize: 14,
                fontWeight: 'bold',
        },
        aiGeneratedBadgeText: {
                color: '#FFF',
                fontSize: 12,
                fontFamily: 'Poppins_700Bold',
                textTransform: 'uppercase',
                textAlign: 'center',
        },
});
