/**
 * All icon names are from MaterialCommunityIcons
 */
export enum IconNames {
    delete_icon = 'delete',
    save_icon = 'content-save',
    confirm_icon = 'check',
    drawer_menu_icon = 'menu',
    drawe_menu_go_back_icon = 'arrow-left',
    canteen_icon = 'warehouse',
    foodoffers_icon = 'silverware-variant',
    building_icon = 'home-city',
    apartments_icon = 'home-account',
    news_icon = 'newspaper',
    course_timetable_icon = 'calendar-clock',
    eating_habit_icon = 'medical-bag',
    settings_icon = 'cog',
    drawer_position_icon = 'menu',
    drawer_position_left_icon = 'format-horizontal-align-left',
    drawer_position_right_icon = 'format-horizontal-align-right',
    settings_system_auto_icon = 'autorenew',
    translate_icon = 'translate',
    profile_nickname_icon = 'account',
    settings_user_account_icon = 'badge-account-horizontal',
    user_account_delete_icon = 'account-remove',
    logout_icon = 'logout',
    sign_in_icon = 'login',
    sign_in_with_mail_icon = 'account-tie',
    debug_icon = 'bug',
    demo_icon_on = 'test-tube',
    demo_icon_off = 'test-tube-empty',
    performance_icon_on = 'speedometer',
    performance_icon_off = 'speedometer-slow',
    color_scheme_icon = 'theme-light-dark',
    color_scheme_light_icon = 'white-balance-sunny',
    color_scheme_dark_icon = 'moon-waning-crescent',
    color_scheme_system_icon = 'theme-light-dark',
    calendar_icon = 'calendar-month',

    utilization_icon = 'human-queue',

    chevron_right_icon = 'chevron-right',
    chevron_left_icon = 'chevron-left',
    color_edit_icon = 'palette',
    news_open_external_icon = 'open-in-new',

    open_link_icon = 'open-in-new',
    phone_icon = 'phone',
    mail_icon = 'email',

    first_weekday_icon = 'calendar-week',
    course_timetable_event_create_icon = 'calendar-plus',
    identifier = 'identifier',
    edit = 'pencil',
    attribute_text_icon = 'tag-text-outline',
    calendar_import_icon = 'calendar-import',
    time_start_icon = 'clock-start',
    time_end_icon = 'clock-end',
    cancel_icon = 'close',

    server_icon = 'server',

    comment_icon = 'chat',
    comment_send_icon = 'send',

    nutrition_icon = 'food-apple',
    nutrition_calories_icon = 'fire',
    nutrition_carbohydrate_icon = 'corn',
    nutrition_fat_icon = 'water',
    nutrition_fiber_icon = 'leaf',
    nutrition_protein_icon = 'fish',
    nutrition_saturated_fat_icon = 'water-circle',
    nutirtion_sodium_icon = 'grain',
    nutrition_sugar_icon = 'cupcake',

    price_group_icon = 'currency-eur',
    price_group_student = 'school',
    price_group_employee = 'briefcase',
    price_group_guest = 'account-group',
    notification_active = "bell",
    notification_inactive = "bell-off",
    favorite_active_icon = "star",
    favorite_inactive_icon = "star-outline",
    heart_active_icon = "heart",
    heart_inactive_icon = "heart-outline",
    dislike_active_icon = "thumb-down",
    dislike_inactive_icon = "thumb-down-outline",
    like_active_icon = "thumb-up",
    like_inactive_icon = "thumb-up-outline",
    star_active_icon = "star",
    star_inactive_icon = "star-outline",
}
