
export enum MyAccessibilityRoles {
    None = 'none',
    Button = 'button',
    ToggleButton = 'togglebutton',
    Link = 'link',
    Search = 'search',
    Image = 'image',
    KeyboardKey = 'keyboardkey',
    Text = 'text',
    Adjustable = 'adjustable',
    ImageButton = 'imagebutton',
    Header = 'header',
    Summary = 'summary',
    Alert = 'alert',
    Checkbox = 'checkbox',
    Combobox = 'combobox',
    Menu = 'menu',
    Menubar = 'menubar',
    MenuItem = 'menuitem',
    ProgressBar = 'progressbar',
    Radio = 'radio',
    RadioGroup = 'radiogroup',
    ScrollBar = 'scrollbar',
    SpinButton = 'spinbutton',
    Switch = 'switch',
    Tab = 'tab',
    TabBar = 'tabbar',
    TabList = 'tablist',
    Timer = 'timer',
    List = 'list',
    Toolbar = 'toolbar'
}
