#!/usr/bin/env python3
"""
Generate TTS voice MP3 files from a JSON definition file using piper-tts.

Runs locally without any API key. Designed for GitHub Actions CI.

Usage:
    python scripts/generate-tts-voices.py

Reads:  apps/geonexia/frontend/assets/tts-generated-voices/voices.json
Writes: apps/geonexia/frontend/assets/tts-generated-voices/<key>.mp3
        apps/geonexia/frontend/assets/tts-generated-voices/generatedVoicesIndex.ts
"""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
VOICES_DIR = REPO_ROOT / "apps" / "geonexia" / "frontend" / "assets" / "tts-generated-voices"
VOICES_JSON = VOICES_DIR / "voices.json"
GENERATED_INDEX = VOICES_DIR / "generatedVoicesIndex.ts"

# ── Piper voice model mapping ─────────────────────────────────────────────────
# Language prefix (first two chars of key) → piper voice model name.
# Models are auto-downloaded by piper on first use.
# See https://github.com/rhasspy/piper#voices for available voices.

LANG_VOICE_MAP: dict[str, str] = {
    "DE": "de_DE-thorsten-high",
    "EN": "en_US-lessac-high",
    "FR": "fr_FR-siwis-medium",
    "ES": "es_ES-sharvard-medium",
    "IT": "it_IT-riccardo-x_low",
    "PT": "pt_BR-faber-medium",
    "NL": "nl_NL-mls-medium",
}

DEFAULT_VOICE = "en_US-lessac-high"


def detect_language(key: str) -> str:
    """Extract language code from the key prefix (e.g. 'DE' from 'DE_de_...')."""
    return key.split("_")[0].upper()


def get_voice_for_key(key: str) -> str:
    """Return the piper voice model for a given key."""
    lang = detect_language(key)
    return LANG_VOICE_MAP.get(lang, DEFAULT_VOICE)


def generate_mp3(text: str, voice: str, output_path: Path) -> bool:
    """Generate an MP3 file from text using piper-tts."""
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as wav_file:
        wav_path = wav_file.name

    try:
        # Generate WAV with piper
        piper_cmd = [
            "piper",
            "--model", voice,
            "--output_file", wav_path,
        ]
        result = subprocess.run(
            piper_cmd,
            input=text,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            print(f"  [ERROR] piper failed: {result.stderr.strip()}")
            return False

        # Convert WAV → MP3 with ffmpeg
        ffmpeg_cmd = [
            "ffmpeg", "-y",
            "-i", wav_path,
            "-codec:a", "libmp3lame",
            "-qscale:a", "2",
            str(output_path),
        ]
        result = subprocess.run(
            ffmpeg_cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode != 0:
            print(f"  [ERROR] ffmpeg failed: {result.stderr.strip()}")
            return False

        return True
    finally:
        if os.path.exists(wav_path):
            os.unlink(wav_path)


def generate_typescript_index(voices: dict[str, str]) -> None:
    """Generate the TypeScript index file with static require() mappings."""
    lines = [
        "// Auto-generated by scripts/generate-tts-voices.py",
        "// Do not edit manually – re-run the generate-tts-voices workflow instead.",
        "",
        "export type GeneratedVoiceEntry = {",
        "\ttext: string;",
        "\taudio: number; // Metro require() asset ID",
        "};",
        "",
        "export const generatedVoices: Record<string, GeneratedVoiceEntry> = {",
    ]

    for key, text in voices.items():
        escaped_text = text.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"\t'{key}': {{")
        lines.append(f"\t\ttext: '{escaped_text}',")
        # eslint-disable-next-line ... is added to avoid require() lint warnings
        lines.append(f"\t\t// eslint-disable-next-line @typescript-eslint/no-require-imports")
        lines.append(f"\t\taudio: require('./{key}.mp3'),")
        lines.append(f"\t}},")

    lines.append("};")
    lines.append("")

    GENERATED_INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated TypeScript index: {GENERATED_INDEX}")


def main() -> None:
    if not VOICES_JSON.exists():
        print(f"ERROR: voices.json not found at {VOICES_JSON}")
        sys.exit(1)

    with open(VOICES_JSON, "r", encoding="utf-8") as f:
        voices: dict[str, str] = json.load(f)

    print(f"Found {len(voices)} voice entries to generate.")

    success_count = 0
    fail_count = 0

    for key, text in voices.items():
        output_path = VOICES_DIR / f"{key}.mp3"
        voice = get_voice_for_key(key)
        lang = detect_language(key)

        print(f"  [{lang}] {key} → {voice}")
        print(f"         \"{text}\"")

        if generate_mp3(text, voice, output_path):
            print(f"         ✓ {output_path.name}")
            success_count += 1
        else:
            print(f"         ✗ FAILED")
            fail_count += 1

    # Generate TypeScript index for all entries (even if some MP3s failed,
    # the require() will simply fail at build time, making the issue visible).
    generate_typescript_index(voices)

    print(f"\nDone: {success_count} succeeded, {fail_count} failed out of {len(voices)}.")
    if fail_count > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
