export const CollectionKeys = {
  MARKINGS_GROUPS: 'markings_groups',
  MARKINGS_EXCLUSIONS: 'markings_exclusions',
  DIRECTUS_COLLECTIONS: 'directus_collections',
  REPORT_RECIPIENTS: 'report_recipients',
  DIRECTUS_COMMENTS: 'directus_comments',
  DIRECTUS_REVISIONS: 'directus_revisions',
  DIRECTUS_FOLDERS: 'directus_folders',
  DIRECTUS_SESSIONS: 'directus_sessions',
  DIRECTUS_FILES: 'directus_files',
  DIRECTUS_PERMISSIONS: 'directus_permissions',
  DIRECTUS_USERS: 'directus_users',
  DIRECTUS_FIELDS: 'directus_fields',
  DIRECTUS_RELATIONS: 'directus_relations',
  DIRECTUS_ACTIVITY: 'directus_activity',
  DIRECTUS_MIGRATIONS: 'directus_migrations',
  DIRECTUS_WEBHOOKS: 'directus_webhooks',
  DIRECTUS_PANELS: 'directus_panels',
  DIRECTUS_NOTIFICATIONS: 'directus_notifications',
  DIRECTUS_SHARES: 'directus_shares',
  DIRECTUS_FLOWS: 'directus_flows',
  DIRECTUS_DASHBOARDS: 'directus_dashboards',
  DIRECTUS_OPERATIONS: 'directus_operations',
  DIRECTUS_TRANSLATIONS: 'directus_translations',
  DIRECTUS_VERSIONS: 'directus_versions',
  DIRECTUS_EXTENSIONS: 'directus_extensions',
  DIRECTUS_SETTINGS: 'directus_settings',
  FOODS_FEEDBACKS_LABELS_TRANSLATIONS: 'foods_feedbacks_labels_translations',
  FORM_EXTRACTS_FORM_FIELDS: 'form_extracts_form_fields',
  FOODS_FEEDBACKS_LABELS: 'foods_feedbacks_labels',
  CANTEEN_FOOD_FEEDBACK_REPORT_SCHEDULES_CANTEENS:
    'canteen_food_feedback_report_schedules_canteens',
  CASHREGISTERS: 'cashregisters',
  FOODS_ATTRIBUTES: 'foods_attributes',
  CANTEEN_FOOD_FEEDBACK_REPORT_SCHEDULES_REPORT_RECIPIENTS:
    'canteen_food_feedback_report_schedules_report_recipients',
  PROFILES_BUILDINGS_FAVORITES: 'profiles_buildings_favorites',
  PROFILES_BUILDINGS_LAST_OPENED: 'profiles_buildings_last_opened',
  MARKINGS_GROUPS_TRANSLATIONS: 'markings_groups_translations',
  WIKIS_DIRECTUS_ROLES: 'wikis_directus_roles',
  WIKIS: 'wikis',
  FORMS: 'forms',
  APP_ELEMENTS: 'app_elements',
  BUILDINGS_ATTRIBUTES: 'buildings_attributes',
  DIRECTUS_ROLES: 'directus_roles',
  DIRECTUS_PRESETS: 'directus_presets',
  LANGUAGES: 'languages',
  FOODS_CATEGORIES: 'foods_categories',
  FOODS_FEEDBACKS_FOODS_FEEDBACKS_LABELS:
    'foods_feedbacks_foods_feedbacks_labels',
  CANTEENS_FEEDBACKS_LABELS: 'canteens_feedbacks_labels',
  FOODOFFERS_CATEGORIES: 'foodoffers_categories',
  DIRECTUS_POLICIES: 'directus_policies',
  DIRECTUS_ACCESS: 'directus_access',
  POPUP_EVENTS_CANTEENS: 'popup_events_canteens',
  DIRECTUS_SYNC_ID_MAP: 'directus_sync_id_map',
  CANTEENS_FEEDBACKS_LABELS_ENTRIES: 'canteens_feedbacks_labels_entries',
  MARKINGS: 'markings',
  BUSINESSHOURS: 'businesshours',
  FILES_SHARES: 'files_shares',
  COLLECTIBLE_EVENTS: 'collectible_events',
  MAILS_FILES: 'mails_files',
  BUILDINGS: 'buildings',
  BUILDINGS_BUSINESSHOURS: 'buildings_businesshours',
  CANTEENS_FOODSERVICE_HOURS: 'canteens_foodservice_hours',
  FOODS_ATTRIBUTES_GROUPS: 'foods_attributes_groups',
  WASHINGMACHINES: 'washingmachines',
  FOODS_FEEDBACKS_LABELS_ENTRIES: 'foods_feedbacks_labels_entries',
  FOODOFFERS_CATEGORIES_TRANSLATIONS: 'foodoffers_categories_translations',
  FORM_EXTRACTS: 'form_extracts',
  APARTMENTS: 'apartments',
  POPUP_EVENTS_TRANSLATIONS: 'popup_events_translations',
  CANTEENS_FOODSERVICE_HOURS_DURING_SEMESTER_BREAK:
    'canteens_foodservice_hours_during_semester_break',
  APP_SETTINGS_HOUSING_TRANSLATIONS: 'app_settings_housing_translations',
  APP_SETTINGS_LOGIN_SCREEN_TRANSLATIONS:
    'app_settings_login_screen_translations',
  WIKIS_TRANSLATIONS: 'wikis_translations',
  BUILDINGS_TRANSLATIONS: 'buildings_translations',
  MARKINGS_TRANSLATIONS: 'markings_translations',
  COLLECTIBLE_EVENTS_TRANSLATIONS: 'collectible_events_translations',
  FOODS_CATEGORIES_TRANSLATIONS: 'foods_categories_translations',
  APP_SETTINGS_BALANCE_TRANSLATIONS: 'app_settings_balance_translations',
  FORMS_TRANSLATIONS: 'forms_translations',
  FORM_CATEGORIES: 'form_categories',
  WASHINGMACHINES_JOBS: 'washingmachines_jobs',
  BUSINESSHOURS_GROUPS: 'businesshours_groups',
  COLLECTIBLE_EVENT_PARTICIPANTS: 'collectible_event_participants',
  FORM_FIELDS: 'form_fields',
  FORM_CATEGORIES_TRANSLATIONS: 'form_categories_translations',
  CANTEENS_FEEDBACKS_LABELS_TRANSLATIONS:
    'canteens_feedbacks_labels_translations',
  BUSINESSHOURS_GROUPS_TRANSLATIONS: 'businesshours_groups_translations',
  FOODS_ATTRIBUTES_TRANSLATIONS: 'foods_attributes_translations',
  FOODS_ATTRIBUTES_GROUPS_TRANSLATIONS: 'foods_attributes_groups_translations',
  FOODS_MARKINGS: 'foods_markings',
  FOODS: 'foods',
  FOODOFFERS: 'foodoffers',
  PROFILES_MARKINGS: 'profiles_markings',
  APP_ELEMENTS_TRANSLATIONS: 'app_elements_translations',
  FORM_ANSWERS: 'form_answers',
  FOODS_ATTRIBUTES_VALUES: 'foods_attributes_values',
  FORM_ANSWERS_FILES: 'form_answers_files',
  FOODS_FEEDBACKS: 'foods_feedbacks',
  FORM_SUBMISSIONS: 'form_submissions',
  MAILS: 'mails',
  PUSH_NOTIFICATIONS: 'push_notifications',
  APP_FEEDBACKS: 'app_feedbacks',
  FORM_FIELDS_TRANSLATIONS: 'form_fields_translations',
  FOODOFFERS_MARKINGS: 'foodoffers_markings',
  WORKFLOWS: 'workflows',
  POPUP_EVENTS: 'popup_events',
  WORKFLOWS_RUNS: 'workflows_runs',
  CASHREGISTERS_TRANSACTIONS: 'cashregisters_transactions',
  PROFILES: 'profiles',
  AUTO_TRANSLATION_SETTINGS: 'auto_translation_settings',
  DEVICES: 'devices',
  CANTEENS: 'canteens',
  FOODS_TRANSLATIONS: 'foods_translations',
  NEWS: 'news',
  NEWS_TRANSLATIONS: 'news_translations',
  UTILIZATIONS_ENTRIES: 'utilizations_entries',
  APP_SETTINGS: 'app_settings',
  UTILIZATIONS_GROUPS: 'utilizations_groups',
  CANTEEN_FOOD_FEEDBACK_REPORT_SCHEDULES:
    'canteen_food_feedback_report_schedules',
};
