const packages = [
  {
    name: '@directus/sdk',
    version: '18.0.0',
    license: 'MIT',
    repository: 'https://github.com/directus/directus',
    licenseUrl: 'https://github.com/directus/directus/raw/master/license',
  },
  {
    name: '@expo-google-fonts/poppins',
    version: '0.2.3',
    license: 'MIT',
    repository: 'https://github.com/expo/google-fonts',
    licenseUrl: 'https://github.com/expo/google-fonts/blob/main/LICENSE',
  },
  {
    name: '@expo/vector-icons',
    version: '14.0.2',
    license: 'MIT',
    repository: 'https://github.com/expo/vector-icons',
    licenseUrl: 'https://github.com/expo/vector-icons/blob/main/LICENSE',
  },
  {
    name: '@gorhom/bottom-sheet',
    version: '5.0.6',
    license: 'MIT',
    repository: 'https://github.com/gorhom/react-native-bottom-sheet',
    licenseUrl:
      'https://github.com/gorhom/react-native-bottom-sheet/blob/main/LICENSE',
  },
  {
    name: '@react-native-async-storage/async-storage',
    version: '1.23.1',
    license: 'MIT',
    repository: 'https://github.com/react-native-async-storage/async-storage',
    licenseUrl:
      'https://github.com/react-native-async-storage/async-storage/blob/master/LICENSE',
  },
  {
    name: '@react-native-picker/picker',
    version: '2.9.0',
    license: 'MIT',
    repository: 'https://github.com/react-native-picker/picker',
    licenseUrl:
      'https://github.com/react-native-picker/picker/blob/master/LICENSE',
  },
  {
    name: '@react-navigation/bottom-tabs',
    version: '7.0.0',
    license: 'MIT',
    repository: 'https://github.com/react-navigation/bottom-tabs',
    licenseUrl:
      'https://github.com/react-navigation/bottom-tabs/blob/main/LICENSE',
  },
  {
    name: '@react-navigation/drawer',
    version: '7.0.0',
    license: 'MIT',
    repository: 'https://github.com/react-navigation/drawer',
    licenseUrl: 'https://github.com/react-navigation/drawer/blob/main/LICENSE',
  },
  {
    name: '@react-navigation/native',
    version: '7.0.0',
    license: 'MIT',
    repository: 'https://github.com/react-navigation/native',
    licenseUrl: 'https://github.com/react-navigation/native/blob/main/LICENSE',
  },
  {
    name: 'axios',
    version: '1.7.7',
    license: 'MIT',
    repository: 'https://github.com/axios/axios',
    licenseUrl: 'https://github.com/axios/axios/blob/master/LICENSE',
  },
  {
    name: 'date-fns',
    version: '4.1.0',
    license: 'MIT',
    repository: 'https://github.com/date-fns/date-fns',
    licenseUrl: 'https://github.com/date-fns/date-fns/blob/main/LICENSE',
  },
  {
    name: 'expo',
    version: '52.0.14',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/master/LICENSE',
  },
  {
    name: 'expo-blur',
    version: '14.0.1',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-blur',
    licenseUrl: 'https://github.com/expo/expo-blur/blob/main/LICENSE',
  },
  {
    name: 'expo-checkbox',
    version: '4.0.0',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-checkbox',
    licenseUrl: 'https://github.com/expo/expo-checkbox/blob/main/LICENSE',
  },
  {
    name: 'expo-constants',
    version: '17.0.3',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-constants',
    licenseUrl: 'https://github.com/expo/expo-constants/blob/main/LICENSE',
  },
  {
    name: 'expo-crypto',
    version: '14.0.1',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-crypto',
    licenseUrl: 'https://github.com/expo/expo-crypto/blob/main/LICENSE',
  },
  {
    name: 'expo-device',
    version: '7.0.1',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-device',
    licenseUrl: 'https://github.com/expo/expo-device/blob/main/LICENSE',
  },
  {
    name: 'expo-font',
    version: '13.0.1',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-font',
    licenseUrl: 'https://github.com/expo/expo-font/blob/main/LICENSE',
  },
  {
    name: 'expo-haptics',
    version: '14.0.0',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-haptics',
    licenseUrl: 'https://github.com/expo/expo-haptics/blob/main/LICENSE',
  },
  {
    name: 'expo-image',
    version: '2.0.3',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-image',
    licenseUrl: 'https://github.com/expo/expo-image/blob/main/LICENSE',
  },
  {
    name: 'expo-image-manipulator',
    version: '12.0.5',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-image-manipulator',
    licenseUrl:
      'https://github.com/expo/expo-image-manipulator/blob/main/LICENSE',
  },
  {
    name: 'expo-image-picker',
    version: '16.0.3',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-image-picker',
    licenseUrl: 'https://github.com/expo/expo-image-picker/blob/main/LICENSE',
  },
  {
    name: 'expo-intent-launcher',
    version: '^12.0.1',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-linking',
    version: '~7.0.3',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-localization',
    version: '~16.0.0',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-notifications',
    version: '^0.29.11',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-router',
    version: '~4.0.11',
    license: 'MIT',
    repository: 'https://github.com/expo/expo-router',
    licenseUrl: 'https://github.com/expo/expo-router/blob/main/LICENSE',
  },
  {
    name: 'expo-secure-store',
    version: '^14.0.0',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-splash-screen',
    version: '~0.29.13',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-status-bar',
    version: '~2.0.0',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-symbols',
    version: '~0.2.0',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-system-ui',
    version: '~4.0.5',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'expo-web-browser',
    version: '~14.0.1',
    license: 'MIT',
    repository: 'https://github.com/expo/expo',
    licenseUrl: 'https://github.com/expo/expo/blob/main/LICENSE',
  },
  {
    name: 'hermes-engine',
    version: '^0.11.0',
    license: 'MIT',
    repository: 'https://github.com/facebook/hermes',
    licenseUrl: 'https://github.com/facebook/hermes/blob/main/LICENSE',
  },
  {
    name: 'i18n-js',
    version: '^4.5.0',
    license: 'MIT',
    repository: 'https://github.com/fnando/i18n-js',
    licenseUrl: 'https://github.com/fnando/i18n-js/blob/master/LICENSE.md',
  },
  {
    name: 'i18next',
    version: '^24.0.5',
    license: 'MIT',
    repository: 'https://github.com/i18next/i18next',
    licenseUrl: 'https://github.com/i18next/i18next/blob/main/LICENSE',
  },
  {
    name: 'react',
    version: '18.3.1',
    license: 'MIT',
    repository: 'https://github.com/facebook/react',
    licenseUrl: 'https://github.com/facebook/react/blob/main/LICENSE',
  },
  {
    name: 'react-dom',
    version: '18.3.1',
    license: 'MIT',
    repository: 'https://github.com/facebook/react',
    licenseUrl: 'https://github.com/facebook/react/blob/main/LICENSE',
  },
  {
    name: 'react-i18next',
    version: '^15.1.2',
    license: 'MIT',
    repository: 'https://github.com/i18next/react-i18next',
    licenseUrl: 'https://github.com/i18next/react-i18next/blob/master/LICENSE',
  },
  {
    name: 'react-native',
    version: '0.76.3',
    license: 'MIT',
    repository: 'https://github.com/facebook/react-native',
    licenseUrl: 'https://github.com/facebook/react-native/blob/main/LICENSE',
  },
  {
    name: 'react-native-calendars',
    version: '^1.1307.0',
    license: 'MIT',
    repository: 'https://github.com/wix/react-native-calendars',
    licenseUrl:
      'https://github.com/wix/react-native-calendars/blob/master/LICENSE',
  },
  {
    name: 'react-native-chart-kit',
    version: '^6.12.0',
    license: 'MIT',
    repository: 'https://github.com/indiespirit/react-native-chart-kit',
    licenseUrl:
      'https://github.com/indiespirit/react-native-chart-kit/blob/master/LICENSE',
  },
  {
    name: 'react-native-collapsible',
    version: '^1.6.2',
    license: 'MIT',
    repository: 'https://github.com/oblador/react-native-collapsible',
    licenseUrl:
      'https://github.com/oblador/react-native-collapsible/blob/master/LICENSE',
  },
  {
    name: 'react-native-gesture-handler',
    version: '~2.20.2',
    license: 'MIT',
    repository:
      'https://github.com/software-mansion/react-native-gesture-handler',
    licenseUrl:
      'https://github.com/software-mansion/react-native-gesture-handler/blob/main/LICENSE',
  },
  {
    name: 'react-native-modal',
    version: '^13.0.1',
    license: 'MIT',
    repository: 'https://github.com/react-native-modal/react-native-modal',
    licenseUrl:
      'https://github.com/react-native-modal/react-native-modal/blob/main/LICENSE',
  },
  {
    name: 'react-native-reanimated',
    version: '~3.16.1',
    license: 'MIT',
    repository: 'https://github.com/software-mansion/react-native-reanimated',
    licenseUrl:
      'https://github.com/software-mansion/react-native-reanimated/blob/main/LICENSE',
  },
  {
    name: 'react-native-root-toast',
    version: '^3.6.0',
    license: 'MIT',
    repository: 'https://github.com/magicismight/react-native-root-toast',
    licenseUrl:
      'https://github.com/magicismight/react-native-root-toast/blob/master/LICENSE',
  },
  {
    name: 'react-native-safe-area-context',
    version: '4.12.0',
    license: 'MIT',
    repository: 'https://github.com/th3rdwave/react-native-safe-area-context',
    licenseUrl:
      'https://github.com/th3rdwave/react-native-safe-area-context/blob/main/LICENSE',
  },
  {
    name: 'react-native-screens',
    version: '~4.1.0',
    license: 'MIT',
    repository: 'https://github.com/software-mansion/react-native-screens',
    licenseUrl:
      'https://github.com/software-mansion/react-native-screens/blob/main/LICENSE',
  },
  {
    name: 'react-native-svg',
    version: '15.8.0',
    license: 'MIT',
    repository: 'https://github.com/react-native-svg/react-native-svg',
    licenseUrl:
      'https://github.com/react-native-svg/react-native-svg/blob/main/LICENSE',
  },
  {
    name: 'react-native-svg-transformer',
    version: '^1.5.0',
    license: 'MIT',
    repository: 'https://github.com/jesstelford/react-native-svg-transformer',
    licenseUrl:
      'https://github.com/jesstelford/react-native-svg-transformer/blob/master/LICENSE',
  },
  {
    name: 'react-native-web',
    version: '~0.19.13',
    license: 'MIT',
    repository: 'https://github.com/necolas/react-native-web',
    licenseUrl: 'https://github.com/necolas/react-native-web/blob/main/LICENSE',
  },
  {
    name: 'react-native-webview',
    version: '13.12.2',
    license: 'MIT',
    repository: 'https://github.com/react-native-webview/react-native-webview',
    licenseUrl:
      'https://github.com/react-native-webview/react-native-webview/blob/main/LICENSE',
  },
  {
    name: 'react-redux',
    version: '^9.1.2',
    license: 'MIT',
    repository: 'https://github.com/reduxjs/react-redux',
    licenseUrl: 'https://github.com/reduxjs/react-redux/blob/main/LICENSE',
  },
  {
    name: 'redux',
    version: '^5.0.1',
    license: 'MIT',
    repository: 'https://github.com/reduxjs/redux',
    licenseUrl: 'https://github.com/reduxjs/redux/blob/main/LICENSE',
  },
  {
    name: 'redux-persist',
    version: '^6.0.0',
    license: 'MIT',
    repository: 'https://github.com/rt2zz/redux-persist',
    licenseUrl: 'https://github.com/rt2zz/redux-persist/blob/main/LICENSE',
  },
  {
    name: 'redux-promise',
    version: '^0.6.0',
    license: 'MIT',
    repository: 'https://github.com/redux-promise/redux-promise',
    licenseUrl:
      'https://github.com/redux-promise/redux-promise/blob/master/LICENSE',
  },
  {
    name: 'redux-thunk',
    version: '^3.1.0',
    license: 'MIT',
    repository: 'https://github.com/reduxjs/redux-thunk',
    licenseUrl: 'https://github.com/reduxjs/redux-thunk/blob/main/LICENSE',
  },
  {
    name: 'reselect',
    version: '^5.1.1',
    license: 'MIT',
    repository: 'https://github.com/reduxjs/reselect',
    licenseUrl: 'https://github.com/reduxjs/reselect/blob/main/LICENSE',
  },
  {
    name: 'tinycolor2',
    version: '^1.6.0',
    license: 'MIT',
    repository: 'https://github.com/bgrins/TinyColor',
    licenseUrl: 'https://github.com/bgrins/TinyColor/blob/master/LICENSE',
  },
  // Add the rest similarly
];

export default packages;
