export const courseTimetableDescriptionEmpty = {
  de: 'Du hast noch keinen **Stundenplan**?\n\nMit unserer Stundenplanfunktion kannst du dein Studium und deine Mahlzeiten wie ein Profi planen. Wenn du ein Profil hast, synchronisieren wir deinen Stundenplan automatisch.\n\n*Hinweis: Wir analysieren ggf. Profile mit Stundenplänen, um überfüllte Essensschlangen zu vermeiden - wir geben diese Daten ggf. nur an dein Studierendenwerk weiter.*\n\n[Mehr darüber](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)',
  en: "You don't have a **timetable** yet?\n\nWith our timetable function you can plan your studies and meals like a pro. If you have a profile, we will automatically synchronize your timetable.\n\n*Note: We may analyze profiles with timetables to avoid crowded food queues - we may only pass on this data to your student union.*\n\n[More about it](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)",
  ar: 'ليس لديك **جدول زمني** بعد؟\n\nمع وظيفة الجدول الزمني لدينا ، يمكنك التخطيط لدراستك ووجباتك مثل محترف. إذا كان لديك ملف تعريف ، سنزامن جدولك الزمني تلقائيًا.\n\n*ملاحظة: قد نحلل الملفات الشخصية التي تحتوي على جداول زمنية لتجنب الطوابير الغذائية المزدحمة - قد نمرر هذه البيانات فقط إلى اتحاد الطلاب.*\n\n[المزيد حول ذلك](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)',
  es: '¿Aún no tienes un **horario**?\n\nCon nuestra función de horario puedes planificar tus estudios y comidas como un profesional. Si tienes un perfil, sincronizaremos automáticamente tu horario.\n\n*Nota: Podemos analizar perfiles con horarios para evitar colas de comida abarrotadas; solo podemos transmitir estos datos a tu unión de estudiantes.*\n\n[Más sobre ello](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)',
  fr: "Vous n'avez pas encore de **planning** ?\n\nAvec notre fonction de planning, vous pouvez planifier vos études et vos repas comme un pro. Si vous avez un profil, nous synchroniserons automatiquement votre planning.\n\n*Remarque : Nous pouvons analyser les profils avec des plannings pour éviter les files d'attente pour la nour riture - nous ne pouvons transmettre ces données qu'à votre union étudiante.*\n\n[En savoir plus](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)",
  ru: 'У вас еще нет **расписания**?\n\nС нашей функцией расписания вы можете планировать свои учебу и еду как профессионал. Если у вас есть профиль, мы автоматически синхронизируем ваше расписание.\n\n*Примечание: Мы можем проанализировать профили с расписаниями, чтобы избежать переполненных очередей за едой - мы можем передавать эти данные только вашему студенческому союзу.*\n\n[Подробнее об этом](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)',
  tr: 'Henüz bir **çizelgeniz** yok mu?\n\nÇizelge işlevimizle çalışmalarınızı ve yemeklerinizi bir profesyonel gibi planlayabilirsiniz. Bir profiliniz varsa, çizelgenizi otomatik olarak senkronize edeceğiz.\n\n*Not: Kalabalık yemek kuyruklarını önlemek için çizelgelerle profilleri analiz edebiliriz - bu verileri yalnızca öğrenci birliğinize iletebiliriz.*\n\n[Hakkında daha fazla](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)',
  zh: '您还没有 **时间表** 吗？\n\n通过我们的时间表功能，您可以像专业人士一样计划您的学习和饮食。如果您有个人资料，我们将自动同步您的时间表。\n\n*注意：我们可能会分析具有时间表的个人资料，以避免拥挤的食物队列 - 我们可能只将这些数据传递给您的学生工会。*\n\n[更多信息](https://nilsbaumgartner.de/homepage/2023/01/15/speiseprognose/)',
};
