name: Expo Update Development
on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/app/**'
      - ".github/workflows/frontend_native_expo_development.yml"

jobs:
  update:
    name: EAS Update Development
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          registry-url: 'https://registry.npmjs.org'

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies with Yarn
        run: cd ./frontend/app && yarn install --frozen-lockfile

      - name: 🚀 Publish development update for branch
        run: cd ./frontend/app && eas update --auto --platform all --non-interactive
